site_name: modbamtools
theme:
  features:
    - content.code.annotate
  name: null
  custom_dir: 'cinder'
  colorscheme: Material
  logo: img/logo.png
repo_url: "https://github.com/rrazaghi/modbamtools"
nav:
  - Home: index.md
  - Commands: commands.md
  - Tutorial: tutorial.md
